/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Daniel Barrios
 */
public class Long extends javax.swing.JFrame {

    /**
     * Creates new form Long
     */
    public Long() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Masa = new javax.swing.JButton();
        Tiem = new javax.swing.JButton();
        Temp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/accidente-automovilistico.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 37, 37, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LONGITUD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 37, 182, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel9.setText("Formulas :");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 332, 142, 44));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 194, 43));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/hogar.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, 49));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("(PI)=PI*304.8");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 120, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("(CM)=MM/10");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 130, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("(M)=CM/100");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(KM)=M/1000");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("(KM)=KM*1000");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 150, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("(YR)=YR*1.094");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 140, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel16.setText("Yardas a X :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel17.setText("Milimetros a X :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel18.setText("Centimetros a X :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel19.setText("Metros a X :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel20.setText("Kilometros a X :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel21.setText("Pies a X :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Concepto de linea recta.");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 20));

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("La distancia es la longitud que un objeto se mueve a lo largo de una trayectoria.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 20));

        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("El desplazamiento es el cambio de posición que experimenta un objeto. ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Ademas La longitud es la cantidad de espacio “lleno” entre el extremo inicial y");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 20));

        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("El final Es importante diferenciarlo del concepto de distancia, que se refiere al");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 20));

        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Espacio vacío entre dos objetos y está estrechamente relacionado con el ");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 700));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel5.setText("Conversor De Unidades");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/operacion.png"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milimetros", "Centimetros", "Metros", "Kilometros", "Pies", "Yardas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milimetros", "Centimetros", "Metros", "Kilometros", "Pies", "Yardas" }));

        jTextField1.setEditable(false);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Convertir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Borrar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/menu-hamburguesa.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/menu-hamburguesa.png"))); // NOI18N

        Masa.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Masa.setText("Masa");
        Masa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Masa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Masa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasaActionPerformed(evt);
            }
        });

        Tiem.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Tiem.setText("Tiempo");
        Tiem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Tiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiemActionPerformed(evt);
            }
        });

        Temp.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Temp.setText("Temperatura");
        Temp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Temp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Masa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tiem, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(Temp, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(Temp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Masa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Tiem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 430, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Interfaz in1 = new Interfaz ();
        in1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String box1 = (String)jComboBox1.getSelectedItem();
        String box2 = (String)jComboBox2.getSelectedItem();

        if (box1.equals("Milimetros")&&box2.equals("Centimetros")){
            double mm = Double.parseDouble(jTextField2.getText());
            double cm = (double)(mm/10);
            jTextField1.setText(String.valueOf(cm));
        }else if (box1.equals("Milimetros")&&box2.equals("Metros")){
            double mm = Double.parseDouble(jTextField2.getText());
            double m = (double)(mm/1000);
            jTextField1.setText(String.valueOf(m));
        }else if (box1.equals("Milimetros")&&box2.equals("Kilometros")){
            double mm = Double.parseDouble(jTextField2.getText());
            double km = (double)(mm/1000000);
            jTextField1.setText(String.valueOf(km));
        }else if (box1.equals("Milimetros")&&box2.equals("Pies")){
            double mm = Double.parseDouble(jTextField2.getText());
            double pi = (double)(mm/304.8);
            jTextField1.setText(String.valueOf(pi));
        }else if (box1.equals("Milimetros")&&box2.equals("Yardas")){
            double mm = Double.parseDouble(jTextField2.getText());
            double yr = (double)(mm/914.4);
            jTextField1.setText(String.valueOf(yr));
        }else if (box1.equals("Milimetros")&&box2.equals("Milimetros")){
            double mm = Double.parseDouble(jTextField2.getText());
            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Metros")&&box2.equals("Milimetros")){
            double m = Double.parseDouble(jTextField2.getText());
            double mm = (double)(m*1000);
            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Metros")&&box2.equals("Centimetros")){
            double m = Double.parseDouble(jTextField2.getText());
            double  cm= (double)(m/100);
            jTextField1.setText(String.valueOf(cm));
        }else if (box1.equals("Metros")&&box2.equals("Kilometros")){
            double m = Double.parseDouble(jTextField2.getText());
            double km = (double)(m/1000);

            jTextField1.setText(String.valueOf(km));
        }else if (box1.equals("Metros")&&box2.equals("Pies")){
            double m = Double.parseDouble(jTextField2.getText());
            double pi = (double)(m*3.281);

            jTextField1.setText(String.valueOf(pi));
        }else if (box1.equals("Metros")&&box2.equals("Yardas")){
            double m = Double.parseDouble(jTextField2.getText());
            double yr = (double)(m*1.094);
            
            jTextField1.setText(String.valueOf(yr));

        }else if (box1.equals("Metros")&&box2.equals("Metros")){
            double m = Double.parseDouble(jTextField2.getText());
            jTextField1.setText(String.valueOf(m));
            
            
          
        }else if (box1.equals("Centimetros")&&box2.equals("Milimetros")){
            double cm = Double.parseDouble(jTextField2.getText());
            double mm = (double)(cm*10);

            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Centimetros")&&box2.equals("Metros")){
            double cm = Double.parseDouble(jTextField2.getText());
            double m = (double)(cm/100);

            jTextField1.setText(String.valueOf(m));
        }else if (box1.equals("Centimetros")&&box2.equals("Kilometros")){
            double cm = Double.parseDouble(jTextField2.getText());
            double km = (double)(cm/100000);

            jTextField1.setText(String.valueOf(km));
        }else if (box1.equals("Centimetros")&&box2.equals("Pies")){
            double cm = Double.parseDouble(jTextField2.getText());
            double pi = (double)(cm/30.48);

            jTextField1.setText(String.valueOf(pi));
        }else if (box1.equals("Centimetros")&&box2.equals("Yardas")){
            double cm = Double.parseDouble(jTextField2.getText());
            double yr = (double)(cm/91.44);

            jTextField1.setText(String.valueOf(yr));
        }else if (box1.equals("Centimetros")&&box2.equals("Centimetros")){
            double cm = Double.parseDouble(jTextField2.getText());

            jTextField1.setText(String.valueOf(cm));
        }else if (box1.equals("Kilometros")&&box2.equals("Milimetros")){
            double km = Double.parseDouble(jTextField2.getText());
            double mm = (double)(km*1000000);
    
            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Kilometros")&&box2.equals("Centimetros")){
            double km = Double.parseDouble(jTextField2.getText());
            double cm = (double)(km*100000);
    
            jTextField1.setText(String.valueOf(cm));
        }else if (box1.equals("Kilometros")&&box2.equals("Metros")){
            double km = Double.parseDouble(jTextField2.getText());
            double m = (double)(km*1000);
    
            jTextField1.setText(String.valueOf(m));
        }else if (box1.equals("Kilometros")&&box2.equals("Kilometros")){
            double km = Double.parseDouble(jTextField2.getText());
            
    
            jTextField1.setText(String.valueOf(km));
        }else if (box1.equals("Kilometros")&&box2.equals("Pies")){
            double km = Double.parseDouble(jTextField2.getText());
            double pi = (double)(km*3280.84);
    
            jTextField1.setText(String.valueOf(pi));
        }else if (box1.equals("Kilometros")&&box2.equals("Yardas")){
            double km = Double.parseDouble(jTextField2.getText());
            double yr = (double)(km*1093.61);
    
            jTextField1.setText(String.valueOf(yr));
        }else if (box1.equals("Pies")&&box2.equals("Milimetros")){
            double pi= Double.parseDouble(jTextField2.getText());
            double mm = (double)(pi*304.8);
    
            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Pies")&&box2.equals("Centimetros")){
            double pi= Double.parseDouble(jTextField2.getText());
            double cm = (double)(pi* 30.48);
    
            jTextField1.setText(String.valueOf(cm));
        } else if (box1.equals("Pies")&&box2.equals("Metros")){
            double pi= Double.parseDouble(jTextField2.getText());
            double m = (double)(pi/ 3.281);
    
            jTextField1.setText(String.valueOf(m));
        }  else if (box1.equals("Pies")&&box2.equals("Kilometros")){
            double pi= Double.parseDouble(jTextField2.getText());
            double km = (double)(pi/  3281);
    
            jTextField1.setText(String.valueOf(km));
        }  else if (box1.equals("Pies")&&box2.equals("Pies")){
            double pi= Double.parseDouble(jTextField2.getText());
    
            jTextField1.setText(String.valueOf(pi));
        } else if (box1.equals("Pies")&&box2.equals("Yardas")){
            double pi= Double.parseDouble(jTextField2.getText());
            double yr = (double)(pi/ 3);
    
            jTextField1.setText(String.valueOf(yr));
        } else if (box1.equals("Yardas")&&box2.equals("Milimetros")){
            double yr= Double.parseDouble(jTextField2.getText());
            double mm = (double)(yr* 914.4);
    
            jTextField1.setText(String.valueOf(mm));
        }else if (box1.equals("Yardas")&&box2.equals("Centimetros")){
            double yr= Double.parseDouble(jTextField2.getText());
            double cm = (double)(yr* 91.44);
    
            jTextField1.setText(String.valueOf(cm));
        }else if (box1.equals("Yardas")&&box2.equals("Metros")){
            double yr= Double.parseDouble(jTextField2.getText());
            double m = (double)(yr/1.094);
    
            jTextField1.setText(String.valueOf(m));
        }else if (box1.equals("Yardas")&&box2.equals("Kilometros")){
            double yr= Double.parseDouble(jTextField2.getText());
            double km = (double)(yr/1094);
    
            jTextField1.setText(String.valueOf(km));
        }else if (box1.equals("Yardas")&&box2.equals("Pies")){
            double yr= Double.parseDouble(jTextField2.getText());
            double pi = (double)(yr*3);
    
            jTextField1.setText(String.valueOf(pi));
        }else if (box1.equals("Yardas")&&box2.equals("Yardas")){
            double yr= Double.parseDouble(jTextField2.getText());
     
            jTextField1.setText(String.valueOf(yr));
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasaActionPerformed
        Masa ms1 = new Masa ();
        ms1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_MasaActionPerformed

    private void TiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiemActionPerformed
        Time tm1 = new Time ();
        tm1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_TiemActionPerformed

    private void TempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempActionPerformed
        Temp tp1 = new Temp ();
        tp1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_TempActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Long.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Long.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Long.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Long.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Long().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Masa;
    private javax.swing.JButton Temp;
    private javax.swing.JButton Tiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
