/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Daniel Barrios
 */
public class Masa extends javax.swing.JFrame {

    /**
     * Creates new form Masa
     */
    public Masa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Temp = new javax.swing.JButton();
        Tiem = new javax.swing.JButton();
        Long = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/operacion.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 40));

        jLabel7.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel7.setText("Conversor De Unidades");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miligramos", "Gramos", "Libras", "Kilogramos", "Toneladas" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 112, 100, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/menu-hamburguesa.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 310, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miligramos", "Gramos", "Libras", "Kilogramos", "Toneladas" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 30));

        jTextField1.setEditable(false);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/menu-hamburguesa.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Convertir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 120, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Showcard Gothic", 2, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Borrar");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, 40));

        Temp.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Temp.setText("Temperatura");
        Temp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Temp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempActionPerformed(evt);
            }
        });
        jPanel3.add(Temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 330, 60));

        Tiem.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Tiem.setText("Tiempo");
        Tiem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Tiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiemActionPerformed(evt);
            }
        });
        jPanel3.add(Tiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 330, 60));

        Long.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        Long.setText("Longitud");
        Long.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Long.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Long.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongActionPerformed(evt);
            }
        });
        jPanel3.add(Long, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 330, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 420, 700));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/igualdad.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 21, -1, 72));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASA");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 34, 114, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 641, 194, 43));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_P/hogar.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 629, -1, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel10.setText("Formulas :");
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 160, 44));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel17.setText("TONELADAS A X :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel18.setText("MILIGRAMOS A X :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel19.setText("GRAMOS A X :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel20.setText("LIBRAS A X :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel21.setText("KILOGRAMOS A X :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("(G)=T*1000000");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 130, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("(G)=MG/1000");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 130, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(KG)=G/1000");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("(G)=LB*453.6");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 130, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("(G)=KG*1000");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 130, 20));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("que expresa la cantidad de materia que hay en un objeto o un cuerpo.");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("La masa es la cantidad de materia o sustancia que posee un cuerpo u objeto ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Material gravedad que sucede en todos los cuerpos. La masa es independiente  ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("de la posición y del estado de movimiento de los cuerpos. Es una propiedad ");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Universal de los cuerpos.");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(" La masa es una magnitud escalar y de uso común en la física y la química,");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Interfaz in1 = new Interfaz ();
        in1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String box1 = (String)jComboBox1.getSelectedItem();
        String box2 = (String)jComboBox2.getSelectedItem();

        if (box1.equals("Miligramos")&&box2.equals("Miligramos")){
            double mg = Double.parseDouble(jTextField2.getText());

            jTextField1.setText(String.valueOf(mg));
        }else if (box1.equals("Miligramos")&&box2.equals("Gramos")){
            double mg = Double.parseDouble(jTextField2.getText());
            double g = (double)(mg/1000);
            jTextField1.setText(String.valueOf(g));
        }else if (box1.equals("Miligramos")&&box2.equals("Libras")){
            double mg = Double.parseDouble(jTextField2.getText());
            double l = (double)(mg/ 453600);
            jTextField1.setText(String.valueOf(l));
        }else if (box1.equals("Miligramos")&&box2.equals("Kilogramos")){
            double mg = Double.parseDouble(jTextField2.getText());
            double kl = (double)(mg/ 1000000);
            jTextField1.setText(String.valueOf(kl));
        }else if (box1.equals("Miligramos")&&box2.equals("Toneladas")){
            double mg = Double.parseDouble(jTextField2.getText());
            double tl = (double)(mg/1000000000);
            jTextField1.setText(String.valueOf(tl));
        }else if (box1.equals("Gramos")&&box2.equals("Miligramos")){
            double g = Double.parseDouble(jTextField2.getText());
            double mg= (double)(g*1000);
            jTextField1.setText(String.valueOf(mg));
        }else if (box1.equals("Gramos")&&box2.equals("Gramos")){
            double g = Double.parseDouble(jTextField2.getText());
   
            jTextField1.setText(String.valueOf(g));
        }else if (box1.equals("Gramos")&&box2.equals("Libras")){
            double g = Double.parseDouble(jTextField2.getText());
            double l= (double)(g/453.6);
            jTextField1.setText(String.valueOf(l));
        }else if (box1.equals("Gramos")&&box2.equals("Kilogramos")){
            double g = Double.parseDouble(jTextField2.getText());
            double kl= (double)(g/1000);
            jTextField1.setText(String.valueOf(kl));
        }else if (box1.equals("Gramos")&&box2.equals("Toneladas")){
            double g = Double.parseDouble(jTextField2.getText());
            double tl= (double)(g/1000000);
            jTextField1.setText(String.valueOf(tl));
        }else if (box1.equals("Libras")&&box2.equals("Miligramos")){
            double l = Double.parseDouble(jTextField2.getText());
            double mg= (double)(l*453600);
            jTextField1.setText(String.valueOf(mg));
        }else if (box1.equals("Libras")&&box2.equals("Gramos")){
            double l = Double.parseDouble(jTextField2.getText());
            double g= (double)(l*453.6);
            jTextField1.setText(String.valueOf(g));
        }else if (box1.equals("Libras")&&box2.equals("Libras")){
            double l = Double.parseDouble(jTextField2.getText());
  
            jTextField1.setText(String.valueOf(l));
        }else if (box1.equals("Libras")&&box2.equals("Kilogramos")){
            double l = Double.parseDouble(jTextField2.getText());
            double kg= (double)(l/ 2.205);
            jTextField1.setText(String.valueOf(kg));
        }else if (box1.equals("Libras")&&box2.equals("Toneladas")){
            double l = Double.parseDouble(jTextField2.getText());
            double tl= (double)(l/2205);
            jTextField1.setText(String.valueOf(tl));
        }else if (box1.equals("Kilogramos")&&box2.equals("Miligramos")){
            double kg = Double.parseDouble(jTextField2.getText());
            double mg= (double)(kg*1000000);
            jTextField1.setText(String.valueOf(mg));
        }else if (box1.equals("Kilogramos")&&box2.equals("Gramos")){
            double kg = Double.parseDouble(jTextField2.getText());
            double g= (double)(kg*1000);
            jTextField1.setText(String.valueOf(g));
        }else if (box1.equals("Kilogramos")&&box2.equals("Libras")){
            double kg = Double.parseDouble(jTextField2.getText());
            double l= (double)(kg* 2.205);
            jTextField1.setText(String.valueOf(l));
        }else if (box1.equals("Kilogramos")&&box2.equals("Kilogramos")){
            double kg = Double.parseDouble(jTextField2.getText());

            jTextField1.setText(String.valueOf(kg));
        }else if (box1.equals("Kilogramos")&&box2.equals("Toneladas")){
            double kg = Double.parseDouble(jTextField2.getText());
            double tl= (double)(kg/2205);
            jTextField1.setText(String.valueOf(tl));
        }else if (box1.equals("Toneladas")&&box2.equals("Miligramos")){
            double tl = Double.parseDouble(jTextField2.getText());
            double mg= (double)(tl*1000000000);
            jTextField1.setText(String.valueOf(mg));
        }else if (box1.equals("Toneladas")&&box2.equals("Gramos")){
            double tl = Double.parseDouble(jTextField2.getText());
            double g= (double)(tl*1000000);
            jTextField1.setText(String.valueOf(g));
        }else if (box1.equals("Toneladas")&&box2.equals("Libras")){
            double tl = Double.parseDouble(jTextField2.getText());
            double l= (double)(tl*2205);
            jTextField1.setText(String.valueOf(l));
        }else if (box1.equals("Toneladas")&&box2.equals("Kilogramos")){
            double tl = Double.parseDouble(jTextField2.getText());
            double kl= (double)(tl*1000);
            jTextField1.setText(String.valueOf(kl));
        }else if (box1.equals("Toneladas")&&box2.equals("Toneladas")){
            double tl = Double.parseDouble(jTextField2.getText());
            
            jTextField1.setText(String.valueOf(tl));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempActionPerformed
        Temp tp1 = new Temp ();
        tp1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_TempActionPerformed

    private void TiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiemActionPerformed
        Time tm1 = new Time ();
        tm1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_TiemActionPerformed

    private void LongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongActionPerformed
        Long lg1 = new Long ();
        lg1.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_LongActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Long;
    private javax.swing.JButton Temp;
    private javax.swing.JButton Tiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
